CREATE TABLE IF NOT EXISTS USUARIO (
  ID_USER INTEGER PRIMARY KEY AUTO_INCREMENT,
  NOMBRE_APE VARCHAR(90) NOT NULL,
  USUARIO VARCHAR(30) NOT NULL,
  DOMICILIO VARCHAR(60) NOT NULL,
  PSW VARCHAR(20) NOT NULL,
  MAIL VARCHAR(60) NOT NULL,
  ROL BOOLEAN NOT NULL
);
/*
  ROL 1 ADMIN   / 0 ES COMUN
*/
INSERT INTO USUARIO VALUES (,"Fulani TA","user1","ESTADOS UNIDOS 444","1234","aa@gmail.com",FALSE);
INSERT INTO USUARIO VALUES (,"Fulani TE","3user","La plata 444","1234","aa@gmail.com",FALSE);
INSERT INTO USUARIO VALUES (,"Fulani TI","4user","Juramento 444","1234","aa@gmail.com",FALSE);
INSERT INTO USUARIO VALUES (,"Fulani TO","5user","Jujuy 444","1234","aa@gmail.com",FALSE);

CREATE TABLE IF NOT EXISTS PEDIDO (
  ID_PEDIDO INTEGER PRIMARY KEY AUTO_INCREMENT,
  ID_USER INTEGER,
  T_PAGO INTEGER NOT NULL,
  p_time DATETIME NOT NULL,
  ESTADO INTEGER NOT NULL,
  total INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDO_X_USER (
  ID_PEDIDO_X_USER INTEGER PRIMARY KEY AUTO_INCREMENT,
  ID_PEDIDO INTEGER NOT NULL,
  id_plato INTEGER NOT NULL,
  CANTIDAD INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS PLATO (
  id_plato INTEGER PRIMARY KEY AUTO_INCREMENT,
  NOMBRE_PLATO VARCHAR(90) NOT NULL,
IMAGEN VARCHAR(500) NOT NULL,
PRECIO INTEGER 
);